-- 코드를 입력하세요
SELECT A.FLAVOR FROM FIRST_HALF AS A
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_TOTAL FROM JULY GROUP BY FLAVOR) AS B ON A.FLAVOR = B.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER + SUM_TOTAL) DESC
LIMIT 3