-- 코드를 입력하세요

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK AS B
JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID 
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC