-- 코드를 입력하세요
SELECT USED_GOODS_BOARD.TITLE AS TITLE, USED_GOODS_BOARD.BOARD_ID, REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD 
JOIN USED_GOODS_REPLY ON USED_GOODS_REPLY.BOARD_ID = USED_GOODS_BOARD.BOARD_ID AND DATE_FORMAT(USED_GOODS_BOARD.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY CREATED_DATE, TITLE